# Generated by Django 5.0.3 on 2024-05-07 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='For soft delete purpose')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host_name', models.CharField(max_length=255, verbose_name='Host Name')),
                ('ip_address', models.CharField(max_length=255, verbose_name='IP Address')),
                ('os', models.CharField(max_length=255, verbose_name='OS')),
                ('software', models.CharField(max_length=255, verbose_name='Software')),
                ('other', models.JSONField(default=dict, verbose_name='Other')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Assets',
                'verbose_name_plural': 'Assets',
                'db_table': 'assets',
            },
        ),
    ]
