# Generated by Django 5.0.3 on 2024-05-10 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_assets'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='For soft delete purpose')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.IntegerField(default=0, verbose_name='Number')),
                ('color_code', models.CharField(max_length=20, verbose_name='Hex Color Code')),
                ('other', models.JSONField(blank=True, default=dict, null=True, verbose_name='Other')),
            ],
            options={
                'verbose_name': 'RiskScale',
                'verbose_name_plural': 'RiskScale',
                'db_table': 'risk_scale',
            },
        ),
        migrations.CreateModel(
            name='RiskRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='For soft delete purpose')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('risk_description', models.TextField(help_text='Give a brief summary of the risk.', verbose_name='Risk Description')),
                ('impact_description', models.TextField(help_text='What will happen if the risk is not mitigated or eliminated?.', verbose_name='Impact Description')),
                ('impact_level', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Rate 1 (LOW) to 5 (HIGH).', verbose_name='Impact Level')),
                ('probability_level', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Rate 1 (LOW) to 5 (HIGH).', verbose_name='Probability Level')),
                ('migrations_notes', models.TextField(help_text='What can be done to lower or eliminate the impact or probability?', verbose_name='Migration Notes')),
                ('owner', models.TextField(help_text="Who's responsible?", verbose_name='Owner')),
                ('other', models.JSONField(blank=True, default=dict, null=True, verbose_name='Other')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'RiskRegister',
                'verbose_name_plural': 'RiskRegister',
                'db_table': 'risk_register',
            },
        ),
    ]
