# Generated by Django 5.0.3 on 2024-05-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_riskscale_riskregister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='ip_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='os',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='OS'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='software',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Software'),
        ),
    ]
